name: Traidify Web CI

on:
  push:
    branches: [ development ]

jobs:
  build:
    name: traidify-web
    runs-on: ubuntu-20.04
    steps:
    - name: Building Traidify Web
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/web
          git fetch
          git checkout development
          git pull origin development
          npm install
          npm run build:staging
